"""first

Revision ID: 31a27cb8a772
Revises: 
Create Date: 2025-01-04 11:46:16.353722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31a27cb8a772'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('_jti', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_jti')
    )
    op.create_table('chats',
    sa.Column('_name', sa.String(length=100), nullable=True),
    sa.Column('_is_group', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('_email', sa.String(length=200), nullable=False),
    sa.Column('_first_name', sa.String(length=100), nullable=False),
    sa.Column('_last_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_email')
    )
    op.create_table('chat_messages',
    sa.Column('_user_id', sa.Integer(), nullable=False),
    sa.Column('_chat_id', sa.Integer(), nullable=False),
    sa.Column('_text', sa.Text(), nullable=False),
    sa.Column('_creating_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('_is_read', sa.Boolean(), nullable=False),
    sa.Column('_storage_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chat_matches',
    sa.Column('_user_id', sa.Integer(), nullable=False),
    sa.Column('_chat_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unread_counts',
    sa.Column('_user_chat_match_id', sa.Integer(), nullable=False),
    sa.Column('_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_user_chat_match_id'], ['user_chat_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unread_counts')
    op.drop_table('user_chat_matches')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('chats')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
