"""add cascade for chats

Revision ID: 3b6a58bfe6dd
Revises: bfbe4057a8bf
Create Date: 2023-11-22 15:15:03.663378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6a58bfe6dd'
down_revision: Union[str, None] = 'bfbe4057a8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
