"""New model - `UnreadCount`

Revision ID: 582be53f3fb0
Revises: 
Create Date: 2024-02-27 14:25:11.475184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582be53f3fb0'
down_revision: Union[str, None] = 'cf22a3f4a236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unread_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_chat_match_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_chat_match_id'], ['users_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unread_counts')
    # ### end Alembic commands ###
