"""the `ChatMessage.has_files` changed to the `ChatMessage.storage_id`

Revision ID: 653ac3097ff4
Revises: de838ca94ab3
Create Date: 2024-11-11 17:30:14.296388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '653ac3097ff4'
down_revision: Union[str, None] = 'de838ca94ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_messages', sa.Column('storage_id', sa.Integer(), nullable=True))
    op.drop_column('chats_messages', 'has_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_messages', sa.Column('has_files', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('chats_messages', 'storage_id')
    # ### end Alembic commands ###
