"""Deleted 'unread_counts' table and added 'user_chat_matches.last_seen_message_id' field

Revision ID: 73444367f41d
Revises: 951214715243
Create Date: 2026-02-11 00:46:01.124027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73444367f41d'
down_revision: Union[str, None] = '951214715243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unread_counts')
    op.add_column('user_chat_matches', sa.Column('last_seen_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_chat_matches', 'messages', ['last_seen_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chat_matches', type_='foreignkey')
    op.drop_column('user_chat_matches', 'last_seen_message_id')
    op.create_table('unread_counts',
    sa.Column('user_chat_match_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_chat_match_id'], ['user_chat_matches.id'], name='unread_counts_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
