"""refactoring models

Revision ID: 75d5f22118fd
Revises: 3b6a58bfe6dd
Create Date: 2023-11-22 16:12:19.754207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75d5f22118fd'
down_revision: Union[str, None] = '3b6a58bfe6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_messages', 'creating_datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_messages', 'creating_datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
