"""Added new field - `ChatMessage.is_read`

Revision ID: 96bd818d1a67
Revises: cf22a3f4a236
Create Date: 2024-02-27 22:50:27.504803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bd818d1a67'
down_revision: Union[str, None] = 'cf22a3f4a236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats_messages', 'is_read')
    # ### end Alembic commands ###
