"""Add nullable=False flag to foreign keys

Revision ID: bfbe4057a8bf
Revises: d7b5b26c94f4
Create Date: 2023-11-16 21:14:15.005029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfbe4057a8bf'
down_revision: Union[str, None] = 'd7b5b26c94f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_messages', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('chats_messages', 'chat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users_chats', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users_chats', 'chat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_chats', 'chat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users_chats', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('chats_messages', 'chat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('chats_messages', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
