"""Delete user fields

Revision ID: c934e5efaf42
Revises: d407d545e157
Create Date: 2024-04-28 12:07:27.376240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c934e5efaf42'
down_revision: Union[str, None] = 'd407d545e157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('auth_token', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('auth_token', 'users', ['auth_token'], unique=False)
    # ### end Alembic commands ###
