"""fix_of_previous

Revision ID: d1c6cb91f059
Revises: 73444367f41d
Create Date: 2026-02-11 01:37:03.350440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1c6cb91f059'
down_revision: Union[str, None] = '73444367f41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_chat_matches', 'last_seen_message_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('user_chat_matches_ibfk_3', 'user_chat_matches', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_chat_matches_ibfk_3', 'user_chat_matches', 'messages', ['last_seen_message_id'], ['id'])
    op.alter_column('user_chat_matches', 'last_seen_message_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
