"""Added new model - `UnreadCount`

Revision ID: d407d545e157
Revises: 96bd818d1a67
Create Date: 2024-03-02 11:31:32.029530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd407d545e157'
down_revision: Union[str, None] = '96bd818d1a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unread_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_chat_match_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_chat_match_id'], ['users_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unread_counts')
    # ### end Alembic commands ###
