"""new `ChatMessage.has_files` column

Revision ID: de838ca94ab3
Revises: 09853867d484
Create Date: 2024-11-04 22:47:41.287973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de838ca94ab3'
down_revision: Union[str, None] = '09853867d484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_messages', sa.Column('has_files', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats_messages', 'has_files')
    # ### end Alembic commands ###
